### ISSUE TITLE
Text needs to change colour at 2 mins and 1 min

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#10]
Countdown text should go Orange at 2 mins, and Red (and possibly bold?) at 1 min

**Comment by drewsdunne** [comment]
Alright I can add this

**Comment by drewsdunne** [comment]
This happens already?

**Comment by andyburnett** [comment]
OK, I have narrowed it down. It works correctly on the iphone, and it works correctly when the web client is running. However, as soon as the clock is paused the text on the web client goes back to black.

**Comment by drewsdunne** [comment]
Ahh alright. I think I now how to fix that.
