### ISSUE TITLE
iPad layout doesn't seem to have the ability to set the sound

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#11]
I can't see the link to let me select the sound to be played at the end of the countdown

**Comment by andyburnett** [comment]
Now that I look more closely, it seems as though that link has gone from all devices.

**Comment by drewsdunne** [comment]
Well, that ability was only there before for show, no matter what it is a duck sound. I can add more if you want but I'd have to find them online as I can't use the built in ring-tones.

**Comment by andyburnett** [comment]
Ok, let's stick with the duck for now

**Comment by drewsdunne** [comment]
Alright, the duck seems best and almost excessive to have more, considering it probably doesn't matter what sound goes off as long as the person knows it's over. Plus I kinda like the duck, very unique :)
