### ISSUE TITLE
Rather than show N/A it would be better to show the current value of the time picker

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#13]
In fact, what would be even cooler is if we could trap the onchange event for the time picker and update the website.

**Comment by drewsdunne** [comment]
Alright I could do this pretty easily I believe.

**Comment by drewsdunne** [comment]
Should only the person in control be able to send the changing of the picker view. Because if we have two people at once trying to do that it might get funky.

**Comment by andyburnett** [comment]
Good point. Yes only one person should be able to set the time. I.e. Being in control means that you can set, start, stop and cancel a timer.

**Comment by drewsdunne** [comment]
Alright, yeah I just had to implement that because it went in an infinite loop of setting it if I didn't haha. Don't want that.
