### ISSUE TITLE
When the countdown reaches 0 it should probably pause

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#14]
At the moment, when the timer reaches zero it resets itself.  This could be rather confusing for the presenter, so it would probably be better for it to remain at zero, until the facilitator cancels it.

**Comment by drewsdunne** [comment]
I think what would be better is if I created a new state called "finished" which would basically force all the apps to just present 00:00 and then disable the buttons except for the cancel button.

**Comment by andyburnett** [comment]
Looks good
