### ISSUE TITLE
Find out what has gone wrong with the oAuth for the new firebase location

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#17]
Probably something trivial, we need to double check whether there is an unchecked settings box or something. Let's compare it with the settings for the working oAuth setup

**Comment by drewsdunne** [comment]
Okay I think this just had to do with the credential information never being added to the Firebase input area on firebaseio.com

**Comment by drewsdunne** [comment]
Alright so I set up Firebase the way it should be and it is still not working so it looks like the Google App Project must be set up incorrectly.

**Comment by andyburnett** [comment]
Does it give any kind of error code?

**Comment by drewsdunne** [comment]
Yeah it says the callback URL isn't correct.
