### ISSUE TITLE
Watch uses too much memory

### ISSUE THREAD

**Issue by drewsdunne** [Knowinnovation/kitime#18]
The Watch App appears to use too much memory for the actual watch and causes a crash upon opening a timer.

**Comment by andyburnett** [comment]
You've got to love the irony in that one :-)

Ok, what do you think the minimum features we can fit are?

**Comment by drewsdunne** [comment]
The features I could add most easily without Firebase are probably the stop/starting and the canceling/resetting. Otherwise I'd have to send more data over firebase and that would get tricky and probably very out of sync.
