### ISSUE TITLE
Cancel and start stop buttons are too easy to confus

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#2]
I love the current layout. The time picker is great, and the overall layout is very slick. My only concern with the layout is that (using it right handed) it is too easy to hit cancel when I really wanted start/pause.

I think it would make more sense to have the Start/Pause/Resume as a large button - underneath the time display.  The Cancel button would be a smaller button, only visible when the timer was paused, and further down the screen.  Also, I wonder if it should be called Reset, rather than cancel

**Comment by drewsdunne** [comment]
I can change it to work like this.
