### ISSUE TITLE
Add a soft-stop/hard-stop selector to each timer

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#20]
A soft-stop would allow the clock to continue past 00:00 and count into the negative numbers, it would also not play the sound.

A hard-stop would stop at 00:00 and play the sound

**Comment by dsl101** [comment]
Just a thought on soft-stop - it's probably less confusing to put '+'
rather than '-' once it starts counting up, so that you've had your 3
minutes '+2'...

**Comment by drewsdunne** [comment]
Yeah I like that idea^ counting back upward. It would probably be easier to do also.

**Comment by andyburnett** [comment]
Sounds good, let's try that.
