### ISSUE TITLE
Add the name of the current timer owner to the countdown screen

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#25]
I think it would be useful to know who is controlling a timer.  Probably the easiest way is to insert the owners name somewhere on the countdown screen. Alternatively, if we went to a two line list display, we could insert it there.

**Comment by drewsdunne** [comment]
Yeah I think it would be best included in the TableView, I can add that

**Comment by drewsdunne** [comment]
So I couldn't ask for the name because not everyone may be registered for Google Plus, but I can use their Know Innovation email, which actually might be better because with your company I'm assuming the emails are their names.

**Comment by andyburnett** [comment]
That will be fine.
