### ISSUE TITLE
Watch still doesn't display the countdown

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#27]
The 1.1.1. release doesn't look any different on the watch.

**Comment by drewsdunne** [comment]
Hmm yeah that's the wrong version, I sent you 1.1.2 I believe

**Comment by andyburnett** [comment]
The manifest on the latest one was 1.1.1. However, I may have missed an
email. Can you resend?

Cheers

**Comment by drewsdunne** [comment]
Just sent it again.
