### ISSUE TITLE
Hard stop repeats if the timer wasn't cancelled

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#30]
Set a timer to hard stop.
Run it until a hard stop occurs
Step back into the Timers view
Reenter the timer that had come to a hard stop.
Hard stop sound repeats.

Only way to stop this is to hit the cancel button.

**Comment by drewsdunne** [comment]
Yeah I've been aware of this issue I didn't think you would be exiting until you cancelled. I'll have to think of a creative workaround.

**Comment by andyburnett** [comment]
The problem is that you might have more than one timer running, and need to
go and look at the other one.

**Comment by drewsdunne** [comment]
Yeah I can get a fix for that probably.
