### ISSUE TITLE
When signed out of the app, the timers list still appears

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#32]
I am not sure if this is a bug, or a feature. 

Clicking on the timer - without having signed in - shows the time picker, but nothing else.  Seems a bit odd

**Comment by drewsdunne** [comment]
This is the point. I thought we wanted to add a read only function. Or at least that was the suggestion by the other person that commented on it.

**Comment by andyburnett** [comment]
Ah, I wondered if that was the case. Great. 

And, if it is possible to hide the time picker when not logged in, that would probably be nice. 

Cheers

**Comment by drewsdunne** [comment]
What do you want it to show? The reason I have that there is so people can see what is being selected.

**Comment by drewsdunne** [comment]
I guess I could make it work like the website where it just shows a label.

**Comment by drewsdunne** [comment]
This is what I did, thought it would be best

**Comment by andyburnett** [comment]
That's what I would recommend. Probably less confusing.

**Comment by drewsdunne** [comment]
Well that's in the latest version I put in the Dropbox 1.1.95
