### ISSUE TITLE
The 00:00 value is displayed in orange instead of red 

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#34]
When the timer is set to hard stop, the 00:00 value appears in orange instead of red. It is displayed in red on the phone.

**Comment by andyburnett** [comment]
actually this bug seems to be more complex than I thought. Need to investigate in more detail

**Comment by drewsdunne** [comment]
Okay I figured this bug out, what happens is when the clock state goes to finished, the duration returns back to the time selected (even though it stays 00:00 on the display) but I change the color based on the duration. I have added code to say if the clock state is finished, make the label red. This should fix the issue.
