### ISSUE TITLE
Limiting access control to known people

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#5]
I haven't looked into Firebase's rules in any detail, but there must be a way for us to specify who can actually use the app. At the moment, I think, that anyone with a Gmail account could authenticate, and use our system. Ideally, we would provide a list of user names, and Firebase would authenticate against that.

**Comment by drewsdunne** [comment]
This is true, I could restrict it using Google's APIs so only people registered with the knowinnovation domain managed by Google apps can sign in, but is this completely necessary? At the moment only Know Innovation will be using the app, no one else will have access to it really.

**Comment by andyburnett** [comment]
It's probably best for us to solve the problem correctly – now – because I'm sure that there will be some edge case that we haven't thought about, and it will come back and bite us! That, sadly is just the way software works. :-)

**Comment by drewsdunne** [comment]
Alright well from what I can get from the Firebase security rules, we could set it up so either we type in everyone's unique Identifier by hand to the security rules to allow them read/write access. OR, we could do it a little differently and give you and I access to an admin app, so people can request access to the regular app from the regular app, and then in our admin app, it would add the user to the approved list if we approve the request. Then they would have access

**Comment by andyburnett** [comment]
Hmm,
Let's go for the simple option - list people by hand - for now. But I like the idea of an admin client.

**Comment by drewsdunne** [comment]
Alright, I can do that, I'll need the people's UIDs once they authenticate using Google.

**Comment by drewsdunne** [comment]
Alright so that actually doesn't work for some odd reason, although it makes sense. But I went ahead and just restricted it so you need a @knowinnovation.com email to sign in and use the app.

**Comment by andyburnett** [comment]
Great
