### ISSUE TITLE
When taking control of a timer, the timer should continue running

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#7]
Take control works really well. And, if a timer is running, it should continue running when I take control.

**Comment by drewsdunne** [comment]
I believe this already happens, when I use take control it just alters the buttons, the timer keeps going on my devices. Is something happening differently on yours?

**Comment by andyburnett** [comment]
We need to double check this. I - think - that when you were running the timer, and I took control, the timer was paused. However, I am not certain about this.

**Comment by drewsdunne** [comment]
It may have been a lag thing. Often what I'll see is when something changes (the duration or state or something) is that someone is slightly behind the actual time and it kind of lags back to correct itself to match the official time. That's just an internet speed sync issue, can't do much about that unless I speed up the Internet haha. But if you do notice that it actually pauses then see if you can replicate it. It may have been that I actually hit pause when I took control.

**Comment by andyburnett** [comment]
Just checked, and this isn't a problem. It was just a slight lag.
