### ISSUE TITLE
System crashes when deleting a timer

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/kitime#9]
The steps seem to be
1. Create a new timer
2. Set its time, and run it
3. Pause
4. Cancel
5. Switch to a different timer
6. Switch back to the main timer view
7. Swipe to delete

"Could not cast value of type 'NSNull' (0x34af058) to 'NSNumber' (0x26396dc).
(lldb) "

**Comment by drewsdunne** [comment]
Yeah I forgot to remove the observers for all the values in a timer in the database so it tried to read the null one after it was deleted. Fixed this
